---
driver:
  name: dokken
  chef_version: 12.21.26
  privileged: true   # decause Docker needs privs to call SystemD/Upstart to manage services

transport:
  name: dokken

provisioner:
  name: dokken
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%%= !ENV['CI'] %>
  always_update_cookbooks: true


verifier:
  name: inspec

platforms:
  - name: centos
    driver:
      image: centos:6.9
      #(centos 7) pid_one_command: /usr/lib/systemd/systemd
      pid_one_command: /sbin/init
      intermediate_instructions:
        #(centos 7) - RUN yum -y install lsof which systemd-sysv initscripts sudo
        - RUN yum -y install which initscripts sudo
  - name: ubuntu
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -y
        - RUN /usr/bin/apt-get install sudo -y


suites:
  - name: default
    run_list:
      - recipe[motd::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    #attributes:
