---
driver:
  name: dokken
  chef_version: 12.21.26

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: centos-6
    driver:
      image: centos:6.9

suites:
  - name: default
    run_list:
      - recipe[motd::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    #attributes:
